import { RankUser } from './rankSchema';

export const mockRankUsers: RankUser[] = [
  {
    id: '1',
    name: '김철수',
    avatar: null,
    totalMinutes: 1200,
    rank: 1,
    category: 'coding',
  },
  {
    id: '2',
    name: '이영희',
    avatar: null,
    totalMinutes: 1050,
    rank: 2,
    category: 'math',
  },
  {
    id: '3',
    name: '박민수',
    avatar: null,
    totalMinutes: 980,
    rank: 3,
    category: 'english',
  },
  {
    id: '4',
    name: '최지은',
    avatar: null,
    totalMinutes: 875,
    rank: 4,
    category: 'science',
  },
  {
    id: '5',
    name: '정현우',
    avatar: null,
    totalMinutes: 820,
    rank: 5,
    category: 'coding',
  },
  {
    id: '6',
    name: '강서연',
    avatar: null,
    totalMinutes: 765,
    rank: 6,
    category: 'reading',
  },
  {
    id: '7',
    name: '윤준호',
    avatar: null,
    totalMinutes: 720,
    rank: 7,
    category: 'math',
  },
  {
    id: '8',
    name: '임수진',
    avatar: null,
    totalMinutes: 680,
    rank: 8,
    category: 'english',
  },
  {
    id: '9',
    name: '조민재',
    avatar: null,
    totalMinutes: 645,
    rank: 9,
    category: 'science',
  },
  {
    id: '10',
    name: '한예진',
    avatar: null,
    totalMinutes: 590,
    rank: 10,
    category: 'coding',
  },
];
