import type { Metadata } from 'next';
import '@/shared/styles/css/globals.css';
import Providers from '@/shared/providers';
import AppLayout from '@/shared/layout';
import { geistMono, geistSans } from '@/shared/styles/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
